# Generated by Django 5.0.6 on 2026-04-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
